# See https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI 

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

defaults:
  run:
    shell: bash

jobs:

  macos:

    runs-on: macos-latest

    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display the python version
        run: python -c "import sys; print(sys.version)"

      - name: Initialise Conda
        run: conda init bash

      - name: Install Geostack
        run: |
          conda init bash
          conda create -n geostack
          conda activate geostack
          conda config --add channels conda-forge
          conda install -c geostack/label/dev geostack
          conda install -c conda-forge llvm-openmp
          GeostackTest
