# See https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI 

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

defaults:
  run:
    shell: bash

jobs:

  macos:

    runs-on: macos-latest

    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display the python version
        run: python -c "import sys; print(sys.version)"

      - name: Initialise Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge

      - name: Install Geostack and SAFER dependencies
        shell: bash -el {0}
        run: |
          conda create -n geostack
          conda activate geostack
          conda install -c geostack/label/dev geostack
          conda install -c conda-forge llvm-openmp
          conda create --name safer --clone geostack
          conda activate safer
          conda install -c conda-forge pyproj networkx gdal igraph pytest

      - name: Get Date
        id: get-date
        run: echo "today=$(/bin/date -u '+%Y%m%d')" >> $GITHUB_OUTPUT
        shell: bash

      - name: Cache Conda env
        uses: actions/cache@v2
        with:
          path: ${{ env.CONDA }}/envs
          key:
            conda-${{ runner.os }}--${{ runner.arch }}--${{
            steps.get-date.outputs.today }}-${{
            hashFiles('etc/example-environment-caching.yml') }}-${{ env.CACHE_NUMBER
            }}
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        id: cache

      - name: Test it out
        shell: bash -el {0}
        run: |
          conda activate safer
          python -c "import sys; print(sys.version)"
